apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: belluominus/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: belluominus/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: belluominus/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: belluominus/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: belluominus/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: belluominus/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}